### ISSUE TITLE
Логин и пароль

### ISSUE THREAD

**Issue by 19TNR82** [3dmaksik/chel-region-helpdesk#1]
Развернул докер и не могу понять на каком этапе настройка логина и пароля ? Всю инструкцию пересмотрел нет нигде.

**Comment by 3dmaksik** [comment]
Доброго времени суток. Логин и пароль по умолчанию устанавливается данным [файлом](https://github.com/3dmaksik/chel-region-helpdesk/blob/master/database/seeders/UsersTableSeeder.php)
admin/password
После входа, вы можете изменить в настройках на свой собственный. 
Данная информация принята к сведению и будет добавлена в инструкцию в следующих обновлениях.

**Comment by 3dmaksik** [comment]
[Добавлен логин и пароль в описание](https://github.com/3dmaksik/chel-region-helpdesk/commit/156a4388ad1771180fa130242a47e007a6a8318b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R185)
