### ISSUE TITLE
Не показывает вложения

### ISSUE THREAD

**Issue by 19TNR82** [3dmaksik/chel-region-helpdesk#2]
Создаю тестовую заявку, захожу под администратором в заявку и хочу открыть вложенный скрин получаю ошибку
![chrome_93Agt1EV6V](https://github.com/user-attachments/assets/016988f7-198e-4a57-bd70-34e7fe95f315)
в консоли пишет 
![chrome_apBbPaeeQt](https://github.com/user-attachments/assets/5d80192b-03c1-4959-bfbf-d82faa644a34)

**Comment by 3dmaksik** [comment]
Добрый день.
Покажите вывод папок изображений либо через докер, либо напрямую обратившись к ним
sudo docker compose exec app ls ./app/public/images
sudo docker compose exec app ls ./storage/images

**Comment by 19TNR82** [comment]
ls: cannot access './app/public/images': No such file or directory
вторая строка ничего не говорит

**Comment by 19TNR82** [comment]
решил проблему созданием ссылки в папке public/storage на app/public/images

**Comment by 3dmaksik** [comment]
Согласно скрипту докера данные ссылки создаваться должны были сами, поэтому данное поведение из-за которых создание не произошло необычное.
`sudo docker compose exec app ln -s ./app/public ./storage`
`sudo docker compose exec app ln -s ./app/public/images ./storage/images`

**Comment by 3dmaksik** [comment]
[Исправлено создание символьных ссылок в докере](https://github.com/3dmaksik/chel-region-helpdesk/commit/156a4388ad1771180fa130242a47e007a6a8318b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R119)
