### ISSUE TITLE
Ошибка загрузки нескольких скриншотов

### ISSUE THREAD

**Issue by 19TNR82** [3dmaksik/chel-region-helpdesk#3]
При загрузке 1-2 скрина всё нормально, но как только гружу штук 10 ошибка. Где то можно отрегулировать объём допустимый для загрузки ?
    
       POST http://192.168.0.8/api/help/new 413 (Request Entity Too Large)
send @ estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1
ajax @ estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1
(анонимная) @ estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1
dispatch @ estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1
m.handle @ estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1
estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1 Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at Object.error (estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1:357052)
    at l (estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1:271041)
    at Object.fireWith [as rejectWith] (estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1:271789)
    at E (estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1:323394)
    at XMLHttpRequest.<anonymous> (estartup.min.js?id=df78ce1e2d89a732c7167cf669e8828d:1:325837)

**Comment by 3dmaksik** [comment]
На данный момент допустимый объём расположен в системных файлах если нужна потребность указывать самостоятельно, то сообщите ваше желание об этом, будет вынесено в файл настроек.

**Comment by 19TNR82** [comment]
Конечно хотелось ) + возможность вложить файлы с любым расширением (например для логов)

**Comment by 3dmaksik** [comment]
[Добавлена настройка максимального объёма в докере](https://github.com/3dmaksik/chel-region-helpdesk/commit/d92eec790827d7165263f9ac70923a5027638c08#diff-468589392a73939ec8c3ecc22af894987bfbf52259dcbe823d4e2bc34a969a6fR7)
[Добавлена настройка задания собственного размера любого файла](https://github.com/3dmaksik/chel-region-helpdesk/commit/156a4388ad1771180fa130242a47e007a6a8318b#diff-54c25d5fbf25b9994690d9864e74c314b5dec7390644e3b7c3f5cf864720ddcfR14)
